server:
  port: 8888
spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;DatabaseName=testData
    username: sa
    password: sqlserver
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    
mybatis:

  type-aliases-package: com.example.demo.entity

  mapper-locations: classpath:mapper/*.xml