server:
  port: 8888

#springboot多数据源配置
#数据源1
spring:
  datasource:
    db1:
      max-idle: 10
      min-idle: 5
      initial-size: 5
      jdbc-url: jdbc:sqlserver://localhost:1433;DatabaseName=testData1
      username: sa
      password: sqlserver
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

    db2:
      max-idle: 10
      min-idle: 5
      password: sqlserver
      initial-size: 5
      max-wait: 10000
      jdbc-url: jdbc:sqlserver://localhost:1433;DatabaseName=testData2
      username: sa
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    db3:
      max-idle: 10
      min-idle: 5
      password: sqlserver
      initial-size: 5
      max-wait: 10000
      jdbc-url: jdbc:sqlserver://localhost:1433;DatabaseName=testData
      username: sa
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

mybatis:
  type-aliases-package: com.example.demo.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  mapper-locations: classpath:mapper/*.xml